import { buildFirstFramePrompt,buildLastFramePrompt } from "@/lib/ai/prompts/frame-generate";
import { resolveSlotContents } from "@/lib/ai/prompts/resolver";
import { resolveImageProvider } from "@/lib/ai/provider-factory";
import { ApiError } from "@/lib/api-error";
import { db } from "@/lib/db";
import { shots } from "@/lib/db/schema";
import { runShotBatch } from "@/lib/generation/batch";
import { extractErrorMessage,getEpisodeCharacters,getVersionedUploadDir,ratioToImageOpts } from "@/lib/generation/common";
import type { GenerationInput } from "@/lib/generation/request";
import { getActiveAsset,insertAssetVersion } from "@/lib/shot-asset-utils";
import { eq } from "drizzle-orm";

export async function handleBatchFrameGenerate(input: GenerationInput) {
  return runShotBatch(input, handleSingleFrameGenerate, ["first_frame","last_frame"]);
}

export async function handleSingleFrameGenerate(input: GenerationInput) {
  const { projectId, userId, payload, modelConfig, episodeId } = input;
  const shotId = payload?.shotId as string;
  if (!shotId) {
    throw new ApiError(400, "No shotId provided");
  }
  if (!modelConfig?.image) {
    throw new ApiError(400, "No image model configured");
  }

  const [shot] = await db.select().from(shots).where(eq(shots.id, shotId));
  if (!shot) {
    throw new ApiError(404, "Shot not found");
  }

  // Read prompts from shot_assets — they were generated by the dedicated
  // "生成首尾帧提示词" step. Each shot is independent: no continuity chain.
  const ffAsset = await getActiveAsset(shotId, "first_frame", 0);
  const lfAsset = await getActiveAsset(shotId, "last_frame", 0);
  const startFramePromptText = ffAsset?.prompt || shot.prompt || "";
  const endFramePromptText = lfAsset?.prompt || shot.prompt || "";

  const versionedUploadDir = await getVersionedUploadDir(shot.versionId);
  const shotEpisodeId = episodeId || shot.episodeId;
  const projectCharacters = await getEpisodeCharacters(projectId, shotEpisodeId);

  const characterDescriptions = projectCharacters
    .map((c) => `${c.name}: ${c.description}`)
    .join("\n");

  // Per-shot character filter: only inject refs for characters declared
  // on the first_frame / last_frame asset metadata for this shot.
  const shotCharNameSet = new Set<string>([
    ...(ffAsset?.characters ?? []),
    ...(lfAsset?.characters ?? []),
  ]);
  const filteredChars = shotCharNameSet.size > 0
    ? projectCharacters.filter((c) => c.referenceImage && shotCharNameSet.has(c.name))
    : projectCharacters.filter((c) => c.referenceImage);
  const shotCharRefImages = filteredChars.map((c) => c.referenceImage as string);

  const ai = resolveImageProvider(modelConfig, versionedUploadDir);
  const imageOpts = ratioToImageOpts(payload?.ratio as string | undefined);

  const frameFirstSlots = await resolveSlotContents("frame_generate_first", { userId, projectId });
  const frameLastSlots = await resolveSlotContents("frame_generate_last", { userId, projectId });

  try {
    await db.update(shots).set({ status: "generating" }).where(eq(shots.id, shotId));

    const firstPrompt = buildFirstFramePrompt({
      sceneDescription: shot.prompt || "",
      startFrameDesc: startFramePromptText,
      characterDescriptions,
      slotContents: frameFirstSlots,
    });
    const firstFramePath = await ai.generateImage(firstPrompt, {
      ...imageOpts,
      quality: "hd",
      referenceImages: shotCharRefImages,
    });

    const lastPrompt = buildLastFramePrompt({
      sceneDescription: shot.prompt || "",
      endFrameDesc: endFramePromptText,
      characterDescriptions,
      firstFramePath,
      slotContents: frameLastSlots,
    });
    const lastFramePath = await ai.generateImage(lastPrompt, {
      ...imageOpts,
      quality: "hd",
      referenceImages: [firstFramePath, ...shotCharRefImages],
    });

    await db.update(shots).set({ status: "completed" }).where(eq(shots.id, shotId));

      await insertAssetVersion({
        shotId,
        type: "first_frame",
        sequenceInType: 0,
        prompt: startFramePromptText,
        characters: filteredChars.map((character) => character.name),
        fileUrl: firstFramePath,
        status: "completed",
      });
      await insertAssetVersion({
        shotId,
        type: "last_frame",
        sequenceInType: 0,
        prompt: endFramePromptText,
        characters: filteredChars.map((character) => character.name),
        fileUrl: lastFramePath,
        status: "completed",
      });

    return { shotId, firstFrame: firstFramePath, lastFrame: lastFramePath, status: "ok" };
  } catch (err) {
    console.error(`[SingleFrameGenerate] Error for shot ${shotId}:`, err);
    await db.update(shots).set({ status: "failed" }).where(eq(shots.id, shotId));
    throw new ApiError(500, extractErrorMessage(err));
  }
}
